apiVersion: v1
kind: ConfigMap
metadata:
  name: teamcity-init-cloud-profile
data:

  project-config.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" uuid="414dc444-b4f0-4a64-a3ca-54386539c2bc" xsi:noNamespaceSchemaLocation="https://www.jetbrains.com/teamcity/schemas/2025.3/project-config.xsd">
      <name>&lt;Root project&gt;</name>
      <description>Contains all other projects</description>
      <project-extensions>
        <extension id="PROJECT_EXT_1" type="ReportTab">
          <parameters>
            <param name="startPage" value="coverage.zip!index.html" />
            <param name="title" value="Code Coverage" />
            <param name="type" value="BuildReportTab" />
          </parameters>
        </extension>
        <extension id="kube-1" type="CloudProfile">
          <parameters>
            <param name="apiServerUrl" value="https://kubernetes.default.svc" />
            <param name="authStrategy" value="service-account" />
            <param name="cloud-code" value="kube" />
            <param name="description" value="" />
            <param name="enabled" value="true" />
            <param name="name" value="test" />
            <param name="namespace" value="wombat-agents" />
            <param name="podTemplateMode" value="notSelected" />
            <param name="profileId" value="kube-1" />
            <param name="profileInstanceLimit" value="10" />
            <param name="profileServerUrl" value="http://teamcity-ha-server.default:8111" />
            <param name="system.cloud.profile_id" value="kube-1" />
            <param name="terminate-idle-time" value="30" />
          </parameters>
        </extension>
      </project-extensions>
      <cleanup>
        <options>
          <option name="preventDependenciesArtifactsFromCleanup" value="false" />
        </options>
      </cleanup>
    </project>
#config/projects/_Root/project-config.xml
