apiVersion: v1
kind: ConfigMap
metadata:
  name: teamcity-kotlin-dsl
data:
  settings.kts: |
    project {
        features {
            kubernetesConnection {
                id = "kube-in-cluster"
                name = "Kubernetes In-Cluster Connection"
                apiServerUrl = "https://kubernetes.default.svc"
                namespace = "wombat-agents"
                authStrategy = serviceAccount()
            }

            kubernetesCloudProfile {
                id = "kube-cloud"
                displayName = "TeamCity K8S Cloud"
                connectionId = "kube-in-cluster"
                agentTemplates {
                    podTemplate {
                        id = "kube-agent-template"
                        name = "Dynamic K8s Agent"
                        image = "jetbrains/teamcity-agent:latest"
                        resources {
                            cpu = 1
                            memoryMb = 2048
                        }
                        idleTimeoutMinutes = 10
                    }
                }
            }
        }
    }
