apiVersion: v1
kind: ConfigMap
metadata:
  name: teamcity-kotlin-dsl
data:
  dep.settings.kts.dep: |
    project {
        features {
            kubernetesConnection {
                id = "kube-in-cluster"
                name = "Kubernetes In-Cluster Connection"
                apiServerUrl = "https://kubernetes.default.svc"
                namespace = "wombat-agents"
                authStrategy = serviceAccount()
            }

            kubernetesCloudProfile {
                id = "kube-cloud"
                displayName = "TeamCity K8S Cloud"
                connectionId = "kube-in-cluster"
                agentTemplates {
                    podTemplate {
                        id = "kube-agent-template"
                        name = "Dynamic K8s Agent"
                        image = "jetbrains/teamcity-agent:latest"
                        resources {
                            cpu = 1
                            memoryMb = 2048
                        }
                        idleTimeoutMinutes = 10
                    }
                }
            }
        }
    }

  settings.kts: |
    project {
        features {
        kubernetesCloudProfile {
            id = "kube-1"
            name = "Kubernetes - ONELOVE"
            apiServerURL = "https://kubernetes.default.svc"
            authStrategy = defaultServiceAccount()
        }
        kubernetesCloudImage {
            id = "PROJECT_EXT_10"
            profileId = "kube-1"
            agentPoolId = "21"
            agentNamePrefix = "k8s-singlec"
            maxInstancesCount = 5
            podSpecification = runContainer {
                dockerImage = "jetbrains/teamcity-agent"
            }
        }
        kubernetesCloudImage {
            id = "PROJECT_EXT_11"
            profileId = "kube-1"
            agentPoolId = "21"
            agentNamePrefix = "k8s-pspec"
            maxInstancesCount = 5
            podSpecification = customTemplate {
                customPod = """
                    apiVersion: v1
                    kind: Pod
                    metadata:
                      labels:
                        app: teamcity-agent
                    spec:
                      restartPolicy: Never
                      containers:
                        - name: teamcity-agent
                          image: jetbrains/teamcity-agent
                          resources:
                            limits:
                              memory: "2Gi"
                """.trimIndent()
            }
          }
        }
    }
