image:
  repository: jetbrains/teamcity-server
  tag: latest
  pullPolicy: Always
  imagePullSecrets: []
agentNamespace: wombat-agents
teamcity:
  namespace: "default"
  resources:
    requests:
      cpu: 100m
      memory: 2048Mi
  env:
    TEAMCITY_SERVER_MEM_OPTS: -Xms512m -Xmx2048m
    POD_NAME:
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
  livenessProbe:
    httpGet:
      path: /healthCheck/healthy
      port: http
      scheme: HTTP
    failureThreshold: 3
    periodSeconds: 30
  readinessProbe:
    httpGet:
      path: /healthCheck/ready
      port: http
      scheme: HTTP
    failureThreshold: 2
    periodSeconds: 10
  ports:
  - containerPort: 8111
    name: http
    protocol: TCP
  affinity: {}
  tolerations:
    - key: "{{ $.Release.Name }}"
      operator: Exists
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app: "{{ $.Release.Name }}"
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app: "{{ $.Release.Name }}"
  nodes:
  - ingress:
      host: teamcity-main.example.com
    ## @param temacity.nodes[<index>].env used to override env per node
    # env:
    #   ROOT_URL: "http://{{ $.Release.Name }}-{{ $index }}.{{ $.Release.Name }}-headless.{{ $.Release.Namespace}}:8111"
    #   NODE_ID: "{{ $.Release.Name }}-{{ $index }}"
    responsibilities:
    - MAIN_NODE
    - CAN_PROCESS_BUILD_TRIGGERS
    - CAN_PROCESS_USER_DATA_MODIFICATION_REQUESTS
    - CAN_CHECK_FOR_CHANGES
    - CAN_PROCESS_BUILD_MESSAGES
  - responsibilities:
    - CAN_PROCESS_BUILD_TRIGGERS
    - CAN_PROCESS_USER_DATA_MODIFICATION_REQUESTS
    - CAN_CHECK_FOR_CHANGES
    - CAN_PROCESS_BUILD_MESSAGES

serviceAccount:
  enabled: true
  annotations: {}
  agentRBAC:
      enabled: false

pdb:
  enabled: true
  minAvailable: 1

pvc:
  name: teamcity-server-data
  annotations:
    helm.sh/resource-policy: keep
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi

persistence:
  enabled: true
  name: teamcity-server-pv
  annotations:
    helm.sh/resource-policy: keep
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  size: 100Gi
## Create & Mount PVC for /opt/teamcity directories
## Defaults to emptyDir
## Generated by STS PVC Template - volume per node
ephemeral:
  temp:
    enabled: false
    annotations: {}
    storageClassName: standard
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 4Gi
  logs:
    enabled: false
    annotations: {}
    storageClassName: standard
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 4Gi
  cache:
    enabled: false
    annotations: {}
    storageClassName: standard
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 4Gi

database:
  host: "10.0.2.15"
  name: "postgres"
  user: "postgres"
  password: "qazwsx" ## TODO

configMap:
  datadirConfig: #TODO MOVE TO SECRET
    database.properties: |
      connectionUrl=jdbc:postgresql://{{ $.Values.database.host }}/{{ .Values.database.name}}?allowPublicKeyRetrieval=true&useSSL=false
      connectionProperties.user={{ $.Values.database.user }}
      connectionProperties.password={{ $.Values.database.password }}
      maxConnections=50
