{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "teamcity-ha.fullname" . }}-ingress
  labels:
    app: {{ include "teamcity-ha.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host.host }}
      http:
        paths:
          - path: {{ $host.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "teamcity-ha.fullname" }}-server
                port:
                  number: {{ $.Values.service.port }}
    {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        - {{ .hosts | join " " }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
{{- end }}
